(use-package cnfonts
  :init
  ;;让 cnfonts 随着 Emacs 自动生效。
  ;; (cnfonts-enable)
  ;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
  ;; (cnfonts-set-spacemacs-fallback-fonts))

  ;; Auto generated by cnfonts
  ;; <https://github.com/tumashu/cnfonts>
  (set-face-attribute
   'default nil
   :font (font-spec :name "-MS  -Consolas-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1"
                    :weight 'normal
                    :slant 'normal
                    :size 11.5))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "-MS  -Microsoft YaHei-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1"
                :weight 'normal
                :slant 'normal
                :size 12.0)))
  )

(provide 'init-fonts)
;;; init-fonts.el ends here
